name: Gradle Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Publish to repository
      run: ./gradlew publish
      env:
        qetzUser: ${{ secrets.REPO_USER }}
        qetzPassword: ${{ secrets.REPO_PASSWORD }}
